env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[8da5e332bd776e2aed19dfbaa57c86820b7fe6c4f3b185cccf0b13f140222c272127fcb5a520b5372f6eebbe53f0e86c]"
  MANIFEST_URL: "https://github.com/SHRP/manifest.git"
  MANIFEST_BRANCH: "v3_11.0"
  DEVICE_TREE_URL: "https://github.com/baunilla/twrp_device_xiaomi_rosy"
  DEVICE_TREE_BRANCH: "android-11"
  DEVICE_PATH: "device/xiaomi/rosy"
  DEVICE_NAME: "rosy"
  MAKEFILE_NAME: "twrp_rosy"
  BUILD_TARGET: "recovery"
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'AnGgIt88'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  sync-recovery_script:
    - mkdir -p ~/.config/rclone
    - echo "$RCLONECONFIG_DRIVE" > ~/.config/rclone/rclone.conf
    - cd $WORKDIR
    - mkdir -p recoverybuild && cd recoverybuild
    - git config --global user.email jarbull87@gmail.com
    - git config --global user.name AnGgIt88
    - repo init --depth=1 --no-repo-verify -u $MANIFEST_URL -b $MANIFEST_BRANCH -g default,-mips,-darwin,-notdefault
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - git clone $DEVICE_TREE_URL -b $DEVICE_TREE_BRANCH $DEVICE_PATH
    - git clone --depth 1 https://github.com/baunilla/android_kernel_xiaomi_rosy -b lineage-20.0 kernel/xiaomi/rosy
    - cd $DEVICE_PATH && git fetch https://github.com/TeamWin/android_device_xiaomi_mithorium-common
    - git cherry-pick ffdb51f3706e3c86f8eecabde5972b890a07b196
    - git cherry-pick b06831f692abb4c999be0ad03a21f61b207651d5
    - git cherry-pick 318ffb8929b98a486a1d1149baf9a430726d9c87

  build-recovery_script:
    - cd $WORKDIR/recoverybuild
    - export ALLOW_MISSING_DEPENDENCIES=true
    - source build/envsetup.sh
    - lunch ${MAKEFILE_NAME}-eng
    - mka ${BUILD_TARGET}image -j8

  upload-recovery_script:
    - cd $WORKDIR/recoverybuild/out/target/product/$DEVICE_NAME
    - recoveryname=$(ls SHRP*-Unofficial*.zip)
    - recoverryaddons=$(ls SHRP_AddonRescue*.zip)
    - rclone copy --drive-chunk-size 256M --stats 1s $recoveryname NFS:recovery/$DEVICE_NAME/twrp -P
    - rclone copy --drive-chunk-size 256M --stats 1s $recoverryaddons NFS:recovery/$DEVICE_NAME/addons -P
